"""alteracao convidado

Revision ID: 2aeed4c8d7c3
Revises: 69baa72b00b8
Create Date: 2022-11-21 22:22:56.572094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aeed4c8d7c3'
down_revision = '69baa72b00b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_convidados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nascimento_primeiro_filho', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('nascimento_segundo_filho', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('logradouro', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('cep', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('bairro', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('cidade', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('zona', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_convidados', schema=None) as batch_op:
        batch_op.drop_column('zona')
        batch_op.drop_column('cidade')
        batch_op.drop_column('bairro')
        batch_op.drop_column('cep')
        batch_op.drop_column('logradouro')
        batch_op.drop_column('nascimento_segundo_filho')
        batch_op.drop_column('nascimento_primeiro_filho')

    # ### end Alembic commands ###
