"""Initial migration convidado.

Revision ID: 69baa72b00b8
Revises: fd443ef53535
Create Date: 2022-11-20 23:35:51.992382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69baa72b00b8'
down_revision = 'fd443ef53535'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_convidados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=True),
    sa.Column('sobrenome', sa.String(), nullable=True),
    sa.Column('nascimento', sa.String(), nullable=True),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('rg', sa.String(), nullable=True),
    sa.Column('uf', sa.String(), nullable=True),
    sa.Column('formacao', sa.String(), nullable=True),
    sa.Column('instituicao', sa.String(), nullable=True),
    sa.Column('semestre', sa.String(), nullable=True),
    sa.Column('periodo', sa.String(), nullable=True),
    sa.Column('estado_civil', sa.String(), nullable=True),
    sa.Column('filhos', sa.Boolean(), nullable=True),
    sa.Column('filho_1', sa.String(), nullable=True),
    sa.Column('filho_2', sa.String(), nullable=True),
    sa.Column('possui_trabalho', sa.Boolean(), nullable=True),
    sa.Column('periodo_trabalho', sa.String(), nullable=True),
    sa.Column('empresa', sa.String(), nullable=True),
    sa.Column('ramo_empresa', sa.String(), nullable=True),
    sa.Column('telefone_empresa', sa.String(), nullable=True),
    sa.Column('telefone_residencial', sa.String(), nullable=True),
    sa.Column('celular', sa.String(), nullable=True),
    sa.Column('operadora', sa.String(), nullable=True),
    sa.Column('plano_operadora', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('pesquisa_de_mercado', sa.Boolean(), nullable=True),
    sa.Column('marketing_publicidade', sa.Boolean(), nullable=True),
    sa.Column('radio_jornal_revista_tv', sa.Boolean(), nullable=True),
    sa.Column('ja_participou', sa.Boolean(), nullable=True),
    sa.Column('tipo_pesquisa', sa.String(), nullable=True),
    sa.Column('data_participacao', sa.String(), nullable=True),
    sa.Column('assunto', sa.String(), nullable=True),
    sa.Column('classificacao_socio', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_convidados')
    # ### end Alembic commands ###
