"""add tb_formulario

Revision ID: a7d1bf5f7f18
Revises: a7eb5fdd5e99
Create Date: 2023-05-21 20:34:55.706023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7d1bf5f7f18'
down_revision = 'a7eb5fdd5e99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_formulario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('pesquisa_id', sa.Integer(), nullable=True),
    sa.Column('pergunta', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['tbl_empresas.id'], ),
    sa.ForeignKeyConstraint(['pesquisa_id'], ['tbl_pesquisas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_formulario')
    # ### end Alembic commands ###
