"""Alterando convidado.

Revision ID: a7eb5fdd5e99
Revises: 2aeed4c8d7c3
Create Date: 2022-11-21 22:37:54.542689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7eb5fdd5e99'
down_revision = '2aeed4c8d7c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_convidados', schema=None) as batch_op:
        batch_op.alter_column('filhos',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('possui_trabalho',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('pesquisa_de_mercado',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('marketing_publicidade',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('radio_jornal_revista_tv',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('ja_participou',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_convidados', schema=None) as batch_op:
        batch_op.alter_column('ja_participou',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
        batch_op.alter_column('radio_jornal_revista_tv',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
        batch_op.alter_column('marketing_publicidade',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
        batch_op.alter_column('pesquisa_de_mercado',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
        batch_op.alter_column('possui_trabalho',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
        batch_op.alter_column('filhos',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
