"""Initial migration convidado.

Revision ID: fd443ef53535
Revises: 
Create Date: 2022-11-20 23:32:37.552130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd443ef53535'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('cnpj', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('tbl_pesquisas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idEmpresa', sa.Integer(), nullable=True),
    sa.Column('objetoPesquisa', sa.String(), nullable=True),
    sa.Column('tipoObjeto', sa.String(), nullable=True),
    sa.Column('dataHoraPesquisa', sa.String(), nullable=True),
    sa.Column('generos', sa.String(), nullable=True),
    sa.Column('faixaEtaria', sa.String(), nullable=True),
    sa.Column('classeEconomica', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_recrutador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('senha', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_recrutador')
    op.drop_table('tbl_pesquisas')
    op.drop_table('tbl_empresas')
    # ### end Alembic commands ###
